//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildIndia.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NasscomEntities : DbContext
    {
        public NasscomEntities()
            : base("name=NasscomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compactor> Compactor { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<Route> Route { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<StaffType> StaffType { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<DeploymentSheet> DeploymentSheet { get; set; }
    }
}
