//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildIndia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compactor
    {
        public int Id { get; set; }
        public string CompactorNumber { get; set; }
        public string Size { get; set; }
        public string Make { get; set; }
        public Nullable<int> LocationId { get; set; }
    }
}
