//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildIndia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentSheet
    {
        public int Id { get; set; }
        public string RouteNumber { get; set; }
        public Nullable<System.DateTime> DeploymentDate { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> Substitute { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> StaffType { get; set; }
    }
}
