//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildIndia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Id { get; set; }
        public string RouteNumber { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> CrewID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public string Location { get; set; }
    }
}
